<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>VehicleNet.VIN</PackageId>
    <Version>1.0.0</Version>
    <Product>VehicleNet.VIN</Product>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VehicleNet.Common\VehicleNet.Common.csproj" />
  </ItemGroup>

</Project>
